server:
  port: 8080

spring:
  datasource:
    #不用写驱动类名，因为java spi
    url: jdbc:mysql://localhost:3306/lvyou_db?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 111111

---
spring:
  config:
    activate:
      on-profile: test
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://localhost:3306/hello?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 111111
management:
  endpoints:
    web:
      exposure:
        include: beans

